# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "dev"]
    types: [opened, reopened, edited, synchronize]
    
 
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate diff
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    
    - name: Get changed files
      id: changed-files
      run: |
        git fetch origin dev
        changed_files=$(git diff --name-only origin/dev...HEAD)
        echo "changed_files=${changed_files}" >> $GITHUB_OUTPUT
    
    - name: Lint with pre-commit
      run: |
        pre-commit --files ${{ steps.changed_files.outputs.changed_files }}
    
    - name: Test with pytest
      run: |
        pytest tests/ --verbose --junit-xml=junit.xml
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
